included:
  - Source
  - Example/Source

file_length:
  warning: 400
  error: 1000
function_body_length:
  warning: 40
  error: 100
identifier_name:
  excluded:
    - id
    - to
    - url
line_length:
  error: 200
  ignores_comments: true
  ignores_function_declarations: true
  warning: 149
type_body_length:
  warning: 200
  error: 350
